[package]
name = "huffman_tree"
version = "0.1.0"
authors = ["Mattias de los Rios Rogers <delosrogers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
